[[new_properties]]
== New Properties

=== General

The SERIES-ID, LAST-SERIES-ID, SDATE and SXDATE properties are
identical in form and in the parameters they take.

All must conform in form to the DTSTART property of the master
component.  Only the SDATE may specify a time which is not part of
the calculated series.

The SRULE property value is identical in form to the RRULE property
defined in <<RFC5545>>.  The LOOKAHEAD-COUNT and LOOKAHEAD-PERIOD
parameters indicate how many instances should be generated in
advance.

[[generating-series-members]]
=== Generating Series members

An agent, either the server or a client, will periodically extend the
set of instances.  The number of such generated instances is limited
by:

Elements of the rule::: The UNTIL or COUNT parts of the rule define
  when the series terminates.  Thus a COUNT=100 specifies a maximum
  of 100 series members.


Lookahead count::: This specifies how many series members can exist
  from the current date/time.  Thus a LOOKAHEAD-COUNT=4 means a
  maximum of 4 generated instances.

Lookahead period::: This specifies how far into the future series
  members can be generated.  Thus a LOOKAHEAD-PERIOD="PT2M" means a
  maximum period of 2 months.

System limits::: This client or server SHOULD also apply limits to
  prevent a series from generating an overlarge set of members.

The starting point for the calculation is the DTSTART of the master
component or the LAST-SERIES-ID if it exists in the master.  In both
cases the instance represented by that date is NOT generated as part
of the instance set and the actual instance may have been excluded by
an SXDATE property but the starting date is still valid.

The starting date/time property defines the first instance in the
next batch of series members.  Note that the starting property value
MUST match the pattern of the series rule, if specified.  For
example, if the rule specifies every Wednesday the starting date MUST
be a Wednesday.

The end date/time of the set will be provided by the UNTIL part of
the rule, the LOOKAHEAD-PERIOD or by a system maxima.

A set of date/time values can be generated within those contraints.
As each date/time value is generated it can be ignored if it is one
of the SXDATE values.

Generation of values can terminate when the size of the result
exceeds that given by the COUNT rule element, the LOOKAHEAD-COUNT
value or any system limit.

Any SDATE values that fall within the current range and are not in
the set of SXDATE values can be added and the result truncated again
to match the size limits.

Finally, any date/time values that have already been generated and
are present as SERIES-ID values should be removed from the set.  What
remains is the new set of members to extend the current series.

The last of those values becomes the new value for the LAST-SERIES-ID
property in the series master.

As noted above the "SXDATE" property can be used to exclude the value
specified in the master.  This leads to a complication as the master
needs to be preserved as a container for the values which define the
series.  This is flagged by adding a DELETED-MASTER element to the
SERIES-STATUS property.

[[prop-series-uid]]
=== Series UID

Property name::: SERIES-UID

Purpose::: This property defines the persistent, globally unique
  identifier for the full series.

Value Type::: TEXT

Property Parameters::: IANA and non-standard property parameters can
  be specified on this property.

Conformance::: This property MUST be specified in any "VEVENT",
  "VTODO", and "VJOURNAL" calendar components acting as a series
  master or series instance.

Description::: The SERIES-UID MUST be globally unique.  This value
  SHOULD be generated by following the recommendations in
  <<RFC7986,section=5.3>>.

Format Definition::
--
This property is defined by the following notation:

[source]
----
seruid        = "SERIES-UID" seruidparam ":" text CRLF

seruidparam   = *(";" other-param)
----
--

[example]
--
The following is an example of this property:

[source]
----
SERIES-UID:123e4567-e89b-12d3-a456-426655440000
----
--

[[prop-series-exception-date]]
=== Series-exception-date

Property name:: SXDATE

Purpose:: This property defines the list of DATE-TIME exceptions for
  series of events, to-dos or journal entries.

Value Type:: The default value type for this property is DATE-TIME.
  The value type can be set to DATE.

Property Parameters:: IANA, non-standard, value data type, and time
  zone identifier property parameters can be specified on this
  property.

Conformance:: This property can be specified in "VEVENT", "VTODO",
  and "VJOURNAL" calendar components acting as the series master.

Description:: The exception dates, if specified, are used when
  computing the instances of the series.  They specify date/time
  values which are to be removed from the set of possible series
  instances.

Format Definition::
--
This property is defined by the following notation:

[source]
----
sxdate     = "SXDATE" sxdtparam ":" sxdtval *("," sxdtval) CRLF

sxdtparam  = *(
           ;
           ; The following are OPTIONAL,
           ; but MUST NOT occur more than once.
           ;
           (";" "VALUE" "=" ("DATE-TIME" / "DATE")) /
           ;
           (";" tzidparam) /
           ;
           ; The following is OPTIONAL,
           ; and MAY occur more than once.
           ;
           (";" other-param)
           ;
           )

sxdtval    = date-time / date
           ;Value MUST match value type
----
--

[example]
--
The following is an example of this property:

[source]
----
SXDATE:19960402T010000Z,19960403T010000Z,19960404T010000Z
----
--

[[prop-series-date]]
=== Series-date

Property name:: SDATE

Purpose:: This property defines the list of DATE-TIME values for
  series of events, to-dos or journal entries.

Value Type:: The default value type for this property is DATE-TIME.
  The value type can be set to DATE.

Property Parameters:: IANA, non-standard, value data type, and time
  zone identifier property parameters can be specified on this
  property.

Conformance:: This property can be specified in "VEVENT", "VTODO",
  and "VJOURNAL" calendar components acting as the series master.

Description:: This property can appear along with the "SRULE"
  property to define a extra series occurrences.  When they both
  appear in a series master component, the instances are defined by
  the union of occurrences defined by both the "SDATE" and "SRULE".

Format Definition::
--
This property is defined by the following notation:

[source]
----
 sdate      = "SDATE" sdtparam ":" sdtval *("," sdtval) CRLF

 sdtparam   = *(
             ;
             ; The following are OPTIONAL,
             ; but MUST NOT occur more than once.
             ;
             (";" "VALUE" "=" ("DATE-TIME" / "DATE" / "PERIOD")) /
             (";" tzidparam) /
             ;
             ; The following is OPTIONAL,
             ; and MAY occur more than once.
             ;
             (";" other-param)
             ;
             )

 sdtval     = date-time / date
             ;Value MUST match value type
----
--

[example]
--
The following are examples of this property:

[source]
----
SDATE:19970714T123000Z
SDATE;TZID=America/New_York:19970714T083000

SDATE;VALUE=PERIOD:19960403T020000Z/19960403T040000Z,
 19960404T010000Z/PT3H

SDATE;VALUE=DATE:19970101,19970120,19970217,19970421
 19970526,19970704,19970901,19971014,19971128,19971129,19971225
----
--


[[prop-series-id]]
=== Series-id

Property name:: SERIES-ID

Purpose:: This property is used in conjunction with the "UID" and
  "SEQUENCE" properties to identify a specific instance of a
  "VEVENT", "VTODO", or "VJOURNAL" calendar component in a series.
  The property value is the original value of the "DTSTART" property
  of the series instance before any changes occur.

Value type:: The default value type is DATE-TIME.  The value type can
  be set to a DATE value type.  This property MUST have the same
  value type as the "DTSTART" property contained within the series
  component.  Furthermore, this property MUST be specified as a date
  with local time if and only if the "DTSTART" property contained
  within the series component is specified as a date with local
  time.

Property Parameters:: IANA, non-standard, value data type and time
  zone identifier parameters can be specified on this property.

Conformance:: This property can be specified zero or more times in
  any iCalendar component.

Description::
--
The SERIES-ID is the originally calculated value of the
  DTSTART property based on the master identified by the RELATED-TO
  property with a RELTYPE=SERIES-MASTER parameter.

  The full series of components can only be retrieved by searching
  for all components with a matching RELATED-TO property.

  If the value of the "DTSTART" property is a DATE type value, then
  the value MUST be the calendar date for the series instance.

  The DATE-TIME value is set to the time when the original series
  instance would occur; meaning that if the intent is to change a
  Friday meeting to Thursday, the DATE-TIME is still set to the
  original Friday meeting.

  The "SERIES-ID" property is used in conjunction with the "UID" and
  "SEQUENCE" properties to identify a particular instance of an
  event, to-do, or journal in the series.  For a given pair of "UID"
  and "SEQUENCE" property values, the "SERIES-ID" value for a series
  instance is fixed.
--

Format Definition::
--
This property is defined by the following notation:

[source]
----
serid    = "SERIES-ID" sidparam ":" sidval CRLF

sidparam   = *(
               ;
               ; The following are OPTIONAL,
               ; but MUST NOT occur more than once.
               ;
               (";" "VALUE" "=" ("DATE-TIME" / "DATE")) /
               (";" tzidparam) /
               ;
               ; The following is OPTIONAL,
               ; and MAY occur more than once.
               ;
               (";" other-param)
               ;
               )

sidval     = date-time / date
               ;Value MUST match value type
----
--

[example]
--
The following are examples of this property:

[source]
----
SERIES-ID;VALUE=DATE:19960401

SERIES-ID;TZID=America/New_York:20170120T120000
----
--


[[prop-last-series-id]]
=== Last series ID

Property name:: LAST-SERIES-ID

Purpose::
--
To specify the last calculated instance of the series.
When new instances are created they MUST have a SERIES-ID after
the value of this property.

In all respects this property is identical to SERIES-ID and is in
fact a copy of the SERIES-ID which would be present in the last
created instance (assuming it is not suppressed by an SXDATE).
--

Value type:: DATE or DATE_TIME (the default).  This has the same
  requirements as SERIES-ID.

Property Parameters:: IANA, non-standard, value data type and time
  zone identifier parameters can be specified on this property.

Conformance:: This property MAY be specified in any iCalendar
  component.

Description:: When used in a component the value of this property
  points to additional information related to the component.  For
  example, it may reference the originating web server.

Format Definition::
--
This property is defined by the following notation:

[source]
----
last-series-i   = "LAST-SERIES-ID" lastseriesidparam  /
                 (
                   ";" "VALUE" "=" "TEXT"
                   ":" text
                 )
                 (
                   ";" "VALUE" "=" "REFERENCE"
                   ":" text
                 )
                 (
                   ";" "VALUE" "=" "URI"
                   ":" uri
                 )
                 CRLF


lastseriesidparam = *(

               ; the following is MANDATORY
               ; and MAY occur more than once

               (";" relparam) /

               ; the following are MANDATORY
               ; but MUST NOT occur more than once

               (";" fmttypeparam) /
               (";" labelparam) /
               ; labelparam is defined in ...

               ; the following is OPTIONAL
               ; and MAY occur more than once

               (";" xparam)

               )
----
--

[example]
--
The following is an example of this property.  It points to a server
acting as the source for the calendar object.

[source]
----
LINK;REL=SOURCE;LABEL=The Egg:http://example.com/events
----
--

[[prop-series-rule]]
=== Series Rule

Property name:: RRULE

Purpose:: This property defines a rule or repeating pattern for a
  series of events, to-dos or journal entries.

Value Type:: RECUR

Property Parameters:: IANA, non-standard, look-ahead count or date
  property parameters can be specified on this property.

Conformance:: This property can be specified in any "VEVENT",
  "VTODO", and "VJOURNAL" calendar component, but it SHOULD NOT be
  specified more than once.

Description::
--
The series rule, if specified, is used in computing the
instances to be generated for the series.  These are generated by
considering the master "DTSTART" property along with the "SRULE",
"SDATE", and "SXDATE" properties contained within the series
master.  The "DTSTART" property defines the first instance in the
recurrence set which is represented by that master event.

Unlike the RRULE the "DTSTART" property MUST be synchronized with
the series rule, if specified.  For example, if the DTSTARTS
species a date on Wednesday but the SRULE specifies every Tuesday
then a server or client MUSt reject the component.

The final series is represented by gathering all of the start
DATE-TIME values generated by any of the specified "SRULE" and
"SDATE" properties, and then excluding any start DATE-TIME values
specified by "SXDATE" properties.  This implies that start DATE-
TIME values specified by "SXDATE" properties take precedence over
those specified by inclusion properties (i.e., "SDATE" and
"SRULE").  Where duplicate instances are generated by the "SRULE"
and "SDATE" properties, only one instance is considered.
Duplicate instances are ignored.

The "DTSTART" property specified within the master iCalendar
object defines the first instance of the recurrence.  In most
cases, a "DTSTART" property of DATE-TIME value type used with a
series rule, should be specified as a date with local time and
time zone reference to make sure all the recurrence instances
start at the same local time regardless of time zone changes.

If the duration of the series component is specified with the
"DTEND" or "DUE" property, then the same exact duration will apply
to all the members of the generated series.  Else, if the duration
of the series master component is specified with the "DURATION"
property, then the same nominal duration will apply to all the
members of the generated series and the exact duration of each
instance will depend on its specific start time.  For example,
series instances of a nominal duration of one day will have an
exact duration of more or less than 24 hours on a day where a time
zone shift occurs.  The duration of a specific instance may be
modified in an exception component or simply by using an "SDATE"
property of PERIOD value type.
--

Format Definition::
--
This property is defined by the following notation:

[source]
----
srule      = "SRULE" srulparam ":" recur CRLF

sruleparam = *(
             ; the following are OPTIONAL
             ; but MUST NOT occur more than once

             (";" lookahead-countparam) /
             (";" lookahead-periodparam) /

             ; the following is OPTIONAL
             ; and MAY occur more than once

             (";" xparam)

             )
----
--

[example]
--
TODO: Say they are pretty much the same as RRULE but extra params
--
